# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#gems: [jekyll-paginate]
#paginate_path: "page:num"
#relative_permalinks: true
plugins: [jekyll-paginate]

# Setup
title:               Rui Dong
tagline:             'The personal website of Rui Dong'
description:         
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              'Rui Dong'
  url:               
  email:             ruiruidong1989@gmail.com

# Custom vars
version:             1.0.0
